# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mypath}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Higginbotham"]
  s.date = %q{2011-07-14}
  s.description = %q{finds a local path corresponding to a given path}
  s.email = %q{daniel@flyingmachinestudios.com}
  s.executables = ["mypath", "mypath"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/mypath",
    "lib/mypath.rb",
    "lib/mypath/handler.rb",
    "lib/mypath/handler/cwd.rb",
    "lib/mypath/handler/gem.rb",
    "mypath.gemspec",
    "spec/dummy_gem_home/gems/dummy_gem-0.0.0/dummy_gem.rb",
    "spec/dummy_local_dir/lib/dummy_lib.rb",
    "spec/handler/cwd_spec.rb",
    "spec/handler/gem_spec.rb",
    "spec/handler_spec.rb",
    "spec/mypath_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/flyingmachine/mypath}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{finds a local path corresponding to a given path}
  s.test_files = [
    "spec/dummy_gem_home/gems/dummy_gem-0.0.0/dummy_gem.rb",
    "spec/dummy_local_dir/lib/dummy_lib.rb",
    "spec/handler/cwd_spec.rb",
    "spec/handler/gem_spec.rb",
    "spec/handler_spec.rb",
    "spec/mypath_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

